# Generated by Django 5.2.1 on 2025-05-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_channel_slow_mode_channel_user_limit_servermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='user_limit',
            field=models.BigIntegerField(default=1000000, help_text='how many users can join this server?'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='user_limit',
            field=models.BigIntegerField(default=1000000, help_text='how many users can join this channel?'),
        ),
    ]
