# Generated by Django 5.2.1 on 2025-05-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_category_server_uid_alter_channel_category_uid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set(),
        ),
    ]
