# Generated by Django 5.2.1 on 2025-05-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_category_uid_alter_channel_uid_alter_role_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag, not actually deleted from the database.'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_private',
            field=models.BooleanField(default=False, help_text='is the category private? (only visible to members with access)'),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag, not actually deleted from the database.'),
        ),
        migrations.AddField(
            model_name='invite',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag, not actually deleted from the database.'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag, not actually deleted from the database.'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag, not actually deleted from the database.'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag, not actually deleted from the database.'),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag, not actually deleted from the database.'),
        ),
    ]
