# Generated by Django 5.2.1 on 2025-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_server_channel_data_servermember_accessible_channels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_data',
            field=models.JSONField(default=dict),
        ),
    ]
