# Generated by Django 5.2.1 on 2025-05-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_category_is_deleted_category_is_private_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='revoked',
        ),
    ]
