# Generated by Django 5.2.1 on 2025-05-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_invite_revoked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='channel_uid',
        ),
    ]
