# Generated by Django 5.2.1 on 2025-05-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_threads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Threads',
            new_name='Thread',
        ),
    ]
