version: "3.9"
services:
  web:
    container_name: projectile_web
    build:
      context: .
      dockerfile: docker/Dockerfile
    # mount the entire repo to get live reload on code changes
    volumes:
      - .:/app
    # ensure we’re in the right folder for manage.py
    working_dir: /app/projectile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - elasticsearch

  db:
    container_name: projectile_db
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: projectile_redis
    image: redis:7
    ports:
      - "6379:6379"

  elasticsearch:
    container_name: projectile_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=${ELASTICSEARCH_DISCOVERY_TYPE}
      - xpack.security.enabled=${ELASTICSEARCH_SECURITY_ENABLED}
      - bootstrap.memory_lock=${ELASTICSEARCH_MEMORY_LOCK}
      - ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data


volumes:
  postgres_data:
  elasticsearch_data: