version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    # mount the entire repo to get live reload on code changes
    volumes:
      - .:/app
    # ensure we’re in the right folder for manage.py
    working_dir: /app/projectile
    command: python manage.py runserver 0.0.0.0:8000
    # command: daphne -b 0.0.0.0 -p 8000 projectile_settings.asgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
