services:
  web:
    container_name: projectile_web
    build:
      context: .
      dockerfile: docker/projectile/Dockerfile
    volumes:
      - .:/app
    working_dir: /app/projectile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    user: "${UID}:${GID}"
    depends_on:
      - db
      - redis
      - elasticsearch
      - chat_service

  chat_service:
    container_name: projectile_chat_service
    build:
      context: .
      dockerfile: docker/chat_service/Dockerfile
    volumes:
      - ./chat_service:/app
    working_dir: /app/app
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db
      # - scylla

  # scylla:
  #   container_name: projectile_scylla
  #   image: scylladb/scylla:5.4
  #   ports:
  #     - "9042:9042"   # native CQL port
  #     - "10000:10000" # REST API (optional)
  #   volumes:
  #     - scylla_data:/var/lib/scylla
  #   environment:
  #     SCYLLA_CLUSTER_NAME: "projectile_cluster"

  db:
    container_name: projectile_db
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: projectile_redis
    image: redis:7
    ports:
      - "6379:6379"

  elasticsearch:
    container_name: projectile_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=${ELASTICSEARCH_DISCOVERY_TYPE}
      - xpack.security.enabled=${ELASTICSEARCH_SECURITY_ENABLED}
      - bootstrap.memory_lock=${ELASTICSEARCH_MEMORY_LOCK}
      - ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  elasticsearch_data:
  # scylla_data:
