# Generated by Django 5.2.1 on 2025-07-30 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0009_alter_category_created_at_alter_channel_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag, not actually deleted from the database.')),
                ('author_uid', models.CharField(blank=True, db_index=True, max_length=36)),
                ('channel_uid', models.CharField(blank=True, db_index=True, max_length=36)),
                ('thread_uid', models.CharField(blank=True, db_index=True, max_length=36)),
                ('content', models.TextField(max_length=5000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_messages', to='server.channel')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='server.thread')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel_uid', 'created_at'], name='message_mes_channel_2283fb_idx'), models.Index(fields=['thread_uid', 'created_at'], name='message_mes_thread__e65c91_idx')],
            },
        ),
    ]
