# Generated by Django 5.2.1 on 2025-05-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_alter_permission_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag, not actually deleted from the database.'),
        ),
    ]
