# Generated by Django 5.2.1 on 2025-12-29 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag, not actually deleted from the database.')),
                ('blocker_uid', models.CharField(blank=True, db_index=True, max_length=36)),
                ('blocked_uid', models.CharField(blank=True, db_index=True, max_length=36)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block_pair')],
            },
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag, not actually deleted from the database.')),
                ('from_user_uid', models.CharField(blank=True, db_index=True, max_length=36)),
                ('to_user_uid', models.CharField(blank=True, db_index=True, max_length=36)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED'), ('cancelled', 'CANCELLED')], db_index=True, default='pending')),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_user_uid', 'created_at'], name='connection__from_us_a7a636_idx'), models.Index(fields=['to_user_uid', 'created_at'], name='connection__to_user_bb387e_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_friend_request_pair')],
            },
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag, not actually deleted from the database.')),
                ('left_user_uid', models.CharField(blank=True, db_index=True, max_length=36)),
                ('right_user_uid', models.CharField(blank=True, db_index=True, max_length=36)),
                ('left_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_left', to=settings.AUTH_USER_MODEL)),
                ('right_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_right', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('left_user', 'right_user'), name='unique_connection_pair')],
            },
        ),
    ]
