# Generated by Django 5.2.1 on 2025-12-29 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='connectionrequest',
            name='unique_friend_request_pair',
        ),
        migrations.RemoveIndex(
            model_name='connectionrequest',
            name='connection__from_us_a7a636_idx',
        ),
        migrations.RemoveIndex(
            model_name='connectionrequest',
            name='connection__to_user_bb387e_idx',
        ),
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='to_user',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='from_user_uid',
            new_name='receiver_uid',
        ),
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='from_user',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='to_user_uid',
            new_name='sender_uid',
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['sender_uid', 'created_at'], name='connection__sender__4e8e53_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['receiver_uid', 'created_at'], name='connection__receive_a065fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='connectionrequest',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_friend_request_pair'),
        ),
    ]
