# Generated by Django 5.2.1 on 2026-01-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_remove_connectionrequest_unique_friend_request_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnection',
            name='last_accepted_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Most recent accept date if connection was soft deleted previously', null=True),
        ),
    ]
