# Generated by Django 5.2.1 on 2026-01-08 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_userconnection_last_accepted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='created_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='connection.userconnection'),
        ),
    ]
