# Generated by Django 5.2.1 on 2025-05-21 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user_uid', models.CharField(db_index=True, max_length=36)),
                ('server_uid', models.CharField(db_index=True, max_length=36)),
                ('accessible_channels', models.JSONField(blank=True, default=dict)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='server.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('member_uid', models.CharField(db_index=True, max_length=36)),
                ('role_uid', models.CharField(db_index=True, max_length=36)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_members', to='server.role')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='member.servermember')),
            ],
        ),
        migrations.AddConstraint(
            model_name='servermember',
            constraint=models.UniqueConstraint(fields=('server', 'user'), name='unique_server_member'),
        ),
        migrations.AddConstraint(
            model_name='memberroles',
            constraint=models.UniqueConstraint(fields=('member', 'role'), name='unique_member_role'),
        ),
    ]
