# Generated by Django 5.2.1 on 2025-05-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberroles',
            name='member_uid',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='memberroles',
            name='role_uid',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='servermember',
            name='server_uid',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='servermember',
            name='user_uid',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
    ]
