# Generated by Django 5.2.1 on 2025-05-22 08:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_memberroles_member_uid_and_more'),
        ('server', '0002_alter_category_server_uid_alter_channel_category_uid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerMember',
            new_name='Member',
        ),
    ]
