# Generated by Django 5.2.1 on 2025-05-26 07:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='uid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='memberroles',
            name='uid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
