# Generated by Django 5.2.1 on 2025-05-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_member_uid_alter_memberroles_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag, not actually deleted from the database.'),
        ),
        migrations.AddField(
            model_name='memberroles',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag, not actually deleted from the database.'),
        ),
    ]
