# Generated by Django 5.2.1 on 2025-05-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_member_is_deleted_memberroles_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
    ]
