STATIC_SPECTRUM_LIST = [
    ("General", "A place for all kinds of conversations"),
    ("Gaming", "Discuss video games and gaming culture"),
    ("Education", "Learning resources and academic topics"),
    ("Technology", "Latest tech news and innovations"),
    ("Programming", "Coding, software development, and debugging"),
    ("Art", "Visual arts, painting, and creativity"),
    ("Design", "Graphic, UI/UX, and product design discussions"),
    ("Movies & TV", "Talk about films, series, and reviews"),
    ("Literature", "Books, poetry, and literary discussions"),
    ("Writing", "Creative and professional writing tips"),
    ("Photography", "Photo sharing and photography techniques"),
    ("Fitness & Health", "Workouts, nutrition, and wellness"),
    ("Mental Health", "Support and discussion around mental wellness"),
    ("Science", "Discoveries and discussion in all sciences"),
    ("Math", "Mathematics help, puzzles, and theories"),
    ("Business", "Entrepreneurship and business strategy"),
    ("Finance", "Personal finance, investing, and markets"),
    ("Crypto", "Cryptocurrency news and trading"),
    ("Startups", "Startup culture and launching ideas"),
    ("Marketing", "Marketing strategies and tips"),
    ("Languages", "Learning and practicing languages"),
    ("Politics", "Political news and debates"),
    ("World News", "Current events from around the globe"),
    ("Philosophy", "Ideas, ethics, and philosophical discussions"),
    ("Religion & Spirituality", "Faith, beliefs, and spirituality"),
    ("Memes", "Humor and viral internet content"),
    ("Roleplay", "Roleplaying games and storytelling"),
    ("Fandom", "Fan communities and discussions"),
    ("Sports", "All kinds of sports and events"),
    ("Cars & Motorsports", "Automotive news and racing"),
    ("Travel", "Destinations, tips, and experiences"),
    ("Food", "Cooking, recipes, and food culture"),
    ("Pets & Animals", "For animal lovers and pet care"),
    ("Environment", "Climate, nature, and sustainability"),
    ("Volunteer & Activism", "Social causes and volunteering"),
    ("Coding Help", "Programming questions and support"),
    ("DevOps", "Infrastructure, deployment, and automation"),
    ("Data Science", "Data analysis, ML, and AI topics"),
    ("AI & Machine Learning", "Artificial intelligence discussions"),
    ("Cybersecurity", "Security news and best practices"),
    ("Web Development", "Frontend and backend web dev"),
    ("Mobile Development", "Apps for Android, iOS, and beyond"),
    ("Game Development", "Building games and game engines"),
]
