# Generated by Django 5.2.1 on 2025-06-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='server_data',
            field=models.JSONField(default=dict),
        ),
    ]
