# Generated by Django 5.1.7 on 2025-03-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('online', 'ONLINE'), ('offline', 'OFFLINE'), ('away', 'AWAY'), ('do not disturb', 'DO NOT DISTURB')], default='offline'),
        ),
    ]
