# Generated by Django 5.2.1 on 2025-07-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_spectrum_options_spectrum_servers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
