# Generated by Django 5.2.1 on 2025-12-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
