# Generated by Django 5.2.1 on 2025-12-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='server_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
