# Generated by Django 5.2.1 on 2025-12-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_metadata_alter_user_server_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='banner_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic_url',
        ),
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
