# Generated by Django 5.1.7 on 2025-03-18 08:06

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
