# Generated by Django 5.2.1 on 2026-01-26 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the health check was performed')),
                ('check_type', models.CharField(choices=[('health', 'HEALTH'), ('readiness', 'READINESS'), ('liveness', 'LIVENESS'), ('unknown', 'UNKNOWN')], db_index=True, default='unknown', help_text='Type of health check performed', max_length=20)),
                ('status', models.CharField(choices=[('healthy', 'HEALTHY'), ('unhealthy', 'UNHEALTHY'), ('degraded', 'DEGRADED'), ('unknown', 'UNKNOWN')], db_index=True, default='unknown', help_text='Resulting status of the health check', max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Time taken in milliseconds', null=True)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Data sent in the health check request')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Data received in the health check response')),
                ('client_type', models.CharField(choices=[('internal', 'INTERNAL'), ('external', 'EXTERNAL'), ('third_party', 'THIRD PARTY'), ('unknown', 'UNKNOWN')], default='unknown', help_text='Broad type of client performing the check', max_length=20)),
                ('client_source', models.CharField(choices=[('kubernetes', 'KUBERNETES'), ('load_balancer', 'LOAD BALANCER'), ('monitoring', 'MONITORING'), ('manual', 'MANUAL'), ('browser', 'BROWSER'), ('unknown', 'UNKNOWN')], default='unknown', help_text='Specific source of the client (e.g., Kubernetes, Load Balancer)', max_length=20)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('unknown', 'UNKNOWN')], default='unknown', help_text='Protocol used for the health check', max_length=10)),
            ],
            options={
                'db_table': 'health_check_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='health_chec_created_a50b9e_idx'), models.Index(fields=['status'], name='health_chec_status_5b10da_idx'), models.Index(fields=['check_type'], name='health_chec_check_t_72007a_idx'), models.Index(fields=['client_type'], name='health_chec_client__ff5f43_idx'), models.Index(fields=['client_source'], name='health_chec_client__1bc912_idx')],
            },
        ),
    ]
